spring:
  application:
    name: accounts-service

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bank
    username : sa
    password: ''

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true




eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/


build:
  version: "1.0"
server:
  port: 8530

